services:

  db:
    image: mysql:latest
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: supersecurepassword
      MYSQL_DATABASE: files
      MYSQL_USER: user
      MYSQL_PASSWORD: securepassword

    ports:
      - 3306:3306

    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
