services:

  db:
    image: mongo:latest
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: supersecurepassword
      MYSQL_DATABASE: files
      MYSQL_USER: user
      MYSQL_PASSWORD: securepassword

    ports:
      - 27017:27017

    volumes:
      - ./db:/data/db

    fsharer:
      build: .
      restart: unless-stopped
      depends_on:
        - mongo
      ports:
        - 5000:5000
      environment:
